import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Simple blog project in NextJS + TailwindCSS + ContentLayer",
  description: "Generated by Jacmilski",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body>
        <header className="flex mx-auto max-w-7xl p-4 border-b-2">
          <ul className="flex grow gap-4 items-center justify-center">
            <li>
              <Link href={"/"}>Home</Link>
            </li>
            <li>
              <Link href={"/about"} >About</Link>
            </li>
            <li>
              <Link href={"/articles"} >Articles</Link>
            </li>
            <li>
              <Link href={"/contact"}>Contact</Link>
            </li>
          </ul>
      </header>
        {children}
      </body>
    </html>
  );
}
